# Generated by Django 3.0 on 2023-03-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_fileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemBillModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(max_length=20)),
                ('iprice', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('total', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='uploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(max_length=20)),
                ('iprice', models.IntegerField()),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
